#!/bin/sh

# PROVIDE: php81_fpm
# REQUIRE: LOGIN
# KEYWORD: shutdown

#
# Add the following line to /etc/rc.conf to enable php-fpm:
# php_fpm_enable (bool):        Set to "NO" by default.
#                               Set it to "YES" to enable php-fpm
# php_fpm_profiles (str):       Set to "" by default.
#                               Define your profiles here.
# php_fpm_pid_prefix (str):     Set to "" by default.
#                               When using profiles manually assign value to "php_fpm_"
#                               for prevent collision with other PIDs names.

. /etc/rc.subr

name="php81_fpm"
rcvar=php81_fpm_enable

start_precmd="php_fpm_prestart"
restart_precmd="php_fpm_checkconfig"
reload_precmd="php_fpm_checkconfig"
command="/opt/php81/sbin/php-fpm"
configtest_cmd="php_fpm_checkconfig"
_pidprefix="/var/run"
pidfile="${_pidprefix}/php81-fpm.pid"
required_files="/opt/php81/etc/php-fpm.conf"

load_rc_config "${name}"

: ${php81_fpm_enable="NO"}
: ${php81_fpm_umask=""}
: ${php81_fpm_svcj_options:="net_basic"}

if [ -n "$2" ]; then
        profile="$2"
        if [ "x${php81_fpm_profiles}" != "x" ]; then
                pidfile="${_pidprefix}/${php81_fpm_pid_prefix}php81-fpm-${profile}.pid"
                eval php81_fpm_configfile="\${php81_fpm_${profile}_configfile:-}"
                if [ "x${php81_fpm_configfile}" = "x" ]; then
                        echo "You must define a configuration file (php81_fpm_${profile}_configfile)"
                        exit 1
                fi
                required_files="${php81_fpm_configfile}"
                eval php81_fpm_enable="\${php81_fpm_${profile}_enable:-${php81_fpm_enable}}"
                php81_fpm_flags="-y ${php81_fpm_configfile} -g ${pidfile}"
        else
                echo "$0: extra argument ignored"
        fi
else
        if [ "x${php81_fpm_profiles}" != "x" -a "x$1" != "x" ]; then
                for profile in ${php81_fpm_profiles}; do
                        echo "===> php81_fpm profile: ${profile}"
                        /usr/local/etc/rc.d/php81-fpm $1 ${profile}
                        retcode="$?"
                        if [ "0${retcode}" -ne 0 ]; then
                                failed="${profile} (${retcode}) ${failed:-}"
                        else
                                success="${profile} ${success:-}"
                        fi
                done
                exit 0
        fi
fi

extra_commands="reload configtest logrotate"
sig_stop="QUIT"
sig_reload="USR2"
logrotate_cmd="php_fpm_logrotate"

php_fpm_logrotate() {
        if [ -z "$rc_pid" ]; then
                _run_rc_notrunning
                return 1
        fi
        echo "Rotating logs $name."
        kill -USR1 $rc_pid
}

php_fpm_checkconfig()
{
        echo "Performing sanity check on php-fpm configuration:"
        eval ${command} ${php81_fpm_flags} -t
}

php_fpm_prestart()
{
	php_fpm_checkconfig
	checkconfig=$?
	if [ $checkconfig -ne 0  ]; then
		return $checkconfig
	fi

	if [ ! -z "$php81_fpm_umask"  ]; then
		echo "Setting umask to: ${php81_fpm_umask}"
		umask $php81_fpm_umask
	fi
}

run_rc_command "$1"
